/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as FeedLayoutRouteImport } from './routes/feed/_layout'
import { Route as FeedSlugIndexRouteImport } from './routes/feed/$slug/index'
import { Route as FeedSlugItemIdRouteImport } from './routes/feed/$slug/item.$id'
import { Route as FeedSlugDocIdRouteImport } from './routes/feed/$slug/doc.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedLayoutRoute = FeedLayoutRouteImport.update({
  id: '/feed/_layout',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugIndexRoute = FeedSlugIndexRouteImport.update({
  id: '/feed/$slug/',
  path: '/feed/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugItemIdRoute = FeedSlugItemIdRouteImport.update({
  id: '/feed/$slug/item/$id',
  path: '/feed/$slug/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugDocIdRoute = FeedSlugDocIdRouteImport.update({
  id: '/feed/$slug/doc/$id',
  path: '/feed/$slug/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/feed': typeof FeedLayoutRoute
  '/feed/': typeof FeedIndexRoute
  '/feed/$slug/': typeof FeedSlugIndexRoute
  '/feed/$slug/doc/$id': typeof FeedSlugDocIdRoute
  '/feed/$slug/item/$id': typeof FeedSlugItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/feed': typeof FeedIndexRoute
  '/feed/$slug': typeof FeedSlugIndexRoute
  '/feed/$slug/doc/$id': typeof FeedSlugDocIdRoute
  '/feed/$slug/item/$id': typeof FeedSlugItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/feed/_layout': typeof FeedLayoutRoute
  '/feed/': typeof FeedIndexRoute
  '/feed/$slug/': typeof FeedSlugIndexRoute
  '/feed/$slug/doc/$id': typeof FeedSlugDocIdRoute
  '/feed/$slug/item/$id': typeof FeedSlugItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/feed'
    | '/feed/'
    | '/feed/$slug/'
    | '/feed/$slug/doc/$id'
    | '/feed/$slug/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/feed'
    | '/feed/$slug'
    | '/feed/$slug/doc/$id'
    | '/feed/$slug/item/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/feed/_layout'
    | '/feed/'
    | '/feed/$slug/'
    | '/feed/$slug/doc/$id'
    | '/feed/$slug/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  FeedLayoutRoute: typeof FeedLayoutRoute
  FeedIndexRoute: typeof FeedIndexRoute
  FeedSlugIndexRoute: typeof FeedSlugIndexRoute
  FeedSlugDocIdRoute: typeof FeedSlugDocIdRoute
  FeedSlugItemIdRoute: typeof FeedSlugItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/_layout': {
      id: '/feed/_layout'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug/': {
      id: '/feed/$slug/'
      path: '/feed/$slug'
      fullPath: '/feed/$slug/'
      preLoaderRoute: typeof FeedSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug/item/$id': {
      id: '/feed/$slug/item/$id'
      path: '/feed/$slug/item/$id'
      fullPath: '/feed/$slug/item/$id'
      preLoaderRoute: typeof FeedSlugItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug/doc/$id': {
      id: '/feed/$slug/doc/$id'
      path: '/feed/$slug/doc/$id'
      fullPath: '/feed/$slug/doc/$id'
      preLoaderRoute: typeof FeedSlugDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  FeedLayoutRoute: FeedLayoutRoute,
  FeedIndexRoute: FeedIndexRoute,
  FeedSlugIndexRoute: FeedSlugIndexRoute,
  FeedSlugDocIdRoute: FeedSlugDocIdRoute,
  FeedSlugItemIdRoute: FeedSlugItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
